#!/bin/bash
UI_WORKING_DIR=$1
jobName=${2:-test}

queue=${4:-cmscaf1nd}

IFS=','
for job in $3
do
	jmin=`echo $job | cut -d '-' -f 1`
	jmax=`echo $job | cut -d '-' -f 2`
	job=`seq -s ',' $jmin $jmax`
	joblist=`echo $joblist,$job | tr ' ' ',' | sed 's|^,||'`
done

nJobs=`tail -1 $UI_WORKING_DIR/share/filelist | cut -d ' ' -f 1`

source ${UI_WORKING_DIR}/share/config

for j in $joblist
do

        echo "resubmitting job $j"
	if grep -s "$j 0" ${UI_WORKING_DIR}/res/$j.status ; then
	    echo "[WARNING `basename $0`] from $j.status file, job $j seems to be successfully done"
	    echo "--> Reset $j.status but you should consider investigating..."
	    echo "" > ${UI_WORKING_DIR}/res/$j.status
	fi

	if grep -s "SUBMITTED" ${UI_WORKING_DIR}/res/$j.status ; then
	    echo "[WARNING `basename $0`] from $j.status file, job $j seems to be already submitted"
	    echo "--> Reset $j.status but you should consider investigating..."
	    echo "" > ${UI_WORKING_DIR}/res/$j.status
	fi

	####first remove the files related to this job if going to be resubmitted
	IFS=$'\n' #### SJ!!! stupid thing needed to make the line below work
	RootFiles=($(grep "xrdcp" ${UI_WORKING_DIR}/res/$j-stdout.log | cut -d " " -f3))
	pathToRootFiles=($(grep "xrdcp" ${UI_WORKING_DIR}/res/$j-stdout.log | cut -d " " -f4 | awk -F "eoscms/" '{print $2}'))
	nFiles=${#RootFiles[@]}
	nPathToRootFiles=${#pathToRootFiles[@]}
	if [ $nFiles -gt 0 ]; then
	    echo "Removing the half copied files first !!! "
	fi
	for (( ifile=0; ifile<${nFiles}; ifile++ ))
	do
	    echo "Removing ${pathToRootFiles[${ifile}]}/${RootFiles[${ifile}]}"
	    rm ${pathToRootFiles[${ifile}]}/${RootFiles[${ifile}]}
	done
	#rm ${UI_WORKING_DIR}/res/$j-std*
	ecalautomation.py -c ${datasetname}  -w ECALELF_prod -e ${extraName} jobctrl --id $j --idle
	submit $UI_WORKING_DIR $jobName $queue  $j
done
