#!/bin/bash
dataset=$1
site=${2:-T2_CH_CERN}
runrange=$3
nEventsMax=${5:-1500000000}

usage(){
	echo "basename $0 datasetpath site nEventsMax"
}

if [ -z "$dataset" ]; then
	echo "[ERROR `basename $0`] No datasetpath in input"
	usage
	exit 1
fi

das_client --query="site dataset=$dataset" | grep $site -q  || {
	echo "[ERROR `basename $0`] dataset $dataset not at $site" >> /dev/stderr
	das_client --query="site dataset=$dataset" >> /dev/stderr
	exit 1
}


if [ -n "$runrange" ];then
	runmin=`echo $runrange | cut -d '-' -f 1`
	runmax=`echo $runrange | cut -d '-' -f 2`
else
	runmin=0
	runmax=999999
fi
query="file dataset=$dataset run between [$runmin,$runmax] status=valid | grep file.name, file.size"

das_client --query="$query" --limit=0  \
 | tr '[' ' ' | tr "'" ' ' | tr "]" " "  | sed 's|,.*"||;s|,.*||;/^$/ d;' | awk '(NF!=0){print $0}' | sort | uniq \
 | awk  -v nEventsMAX=${nEventsMax} 'BEGIN{i=0};(NF!=0){nEvents+=$2; print i,$1,$2,nEvents/nEventsMAX,nEvents,nEventsMAX; if(nEvents>nEventsMAX){i++;nEvents=0}}' 
#  tr -d '[' | tr -d "'" | tr ']' ',' | cut -d ',' -f 1,3 | 

